# What do we want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-elk-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 21Gi
---
# How do we want it implemented
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-elk-disk
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed